### ISSUE TITLE
Oscillation of drone when using Point-LIO with Livox Mid-360 for state estimation

### ISSUE THREAD

**Issue by migsdigs** [hku-mars/Point-LIO#113]
Hi there, 

Thank you very much for open sourcing your work! I have a slight issue with my system that I was hoping you might have had an experience with before. I am looking to use Point-LIO as the main state estimator for my drone. I am also using a simulation of the Livox Mid-360 based on [this](https://github.com/Livox-SDK/livox_laser_simulation). As the simulation of the lidar does not include the imu simulation, I am using the IMU of my px4 flight controller. 

When comparing the state estimation of the Point-LIO to ground truth and GPS, it appears to produce some quite nice, reasonable results. However, when I switch to using Point-LIO as the enabled estimator (from GPS), instead of continuing to hover about its current point, it starts to oscillate in the z-axis, with the oscillations growing in magnitude somewhat exponentially. I am using the below config file:

```
common:
    lid_topic:  "/livox/lidar" 
#    imu_topic:  "/livox/imu"
    imu_topic: "/uav1/hw_api/imu"
    con_frame: false # true: if you need to combine several LiDAR frames into one
    con_frame_num: 1 # the number of frames combined
    cut_frame: false # true: if you need to cut one LiDAR frame into several subframes
    cut_frame_time_interval: 0.1 # should be integral fraction of 1 / LiDAR frequency
    time_lag_imu_to_lidar: 0.0 # Time offset between LiDAR and IMU calibrated by other algorithms, e.g., LI-Init (find in Readme)
                               # the timesample of IMU is transferred from the current timeline to LiDAR's timeline by subtracting this value

preprocess:
    lidar_type: 1 
    scan_line: 4
    timestamp_unit: 1           # the unit of time/t field in the PointCloud2 rostopic: 0-second, 1-milisecond, 2-microsecond, 3-nanosecond.
    blind: 0.5 

mapping:
    imu_en: true
    extrinsic_est_en: false # for aggressive motion, set this variable false
    imu_time_inte: 0.01 # = 1 / frequency of IMU
    satu_acc: 3.0 # the saturation value of IMU's acceleration. not related to the units
    # satu_gyro: 35 # the saturation value of IMU's angular velocity. not related to the units
    acc_norm: 9.810 # 1.0 for g as unit, 9.81 for m/s^2 as unit of the IMU's acceleration
    lidar_meas_cov: 0.01 # 0.001; 0.01
    acc_cov_output: 500
    gyr_cov_output: 1000 
    b_acc_cov: 0.0001 
    b_gyr_cov: 0.0001 
    imu_meas_acc_cov: 0.01 #0.00186 #0.1 #0.1 # 0.1
    imu_meas_omg_cov: 0.1 #0.00018665 #0.1 #0.01 # 0.1
    gyr_cov_input: 0.01 # for IMU as input model
    acc_cov_input: 0.1 # for IMU as input model
    plane_thr: 0.01 # 0.05, the threshold for plane criteria, the smaller, the flatter a plane
    match_s: 81
    fov_degree: 360 
    det_range: 100.0
    gravity_align: true # true to align the z axis of world frame with the direction of gravity, and the gravity direction should be specified below
    gravity: [0.0, 0.0, -9.810] # [0.0, 9.810, 0.0] # gravity to be aligned
    gravity_init: [0.0, 0.0, -9.810] # [0.0, 9.810, 0.0] # # preknown gravity in the first IMU body frame, use when imu_en is false or start from a non-stationary state
    # TODO: is this true for MID360 Livox?
    extrinsic_T: [ 0.0, 0.0, 0.182 ]
    extrinsic_R: [ 1, 0, 0,
                   0, 1, 0,
                   0, 0, 1 ]

odometry: 
    publish_odometry_without_downsample: false

publish:
    path:
      enable: true # false: close the path output
      # TODO: use these values in code
      diff_t: 0.01 # (m) publish when translation has changed by this value
      diff_R: 0.01 # (rad) publish when one of the Euler angles has changed by this value
    scan_publish_en: false       # false: close all the point cloud output
    scan_bodyframe_pub_en: true  # true: output the point cloud scans in IMU-body-frame

pcd_save:
    pcd_save_en: false
    interval: -1                 # how many LiDAR frames saved in each pcd file; 
                                 # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
```

Is there anything that you can recommend based on your experience, or anything you can see in my config file that would be obviously wrong? I have configured the extrinsic matrix according to the echoed tf between the IMU frame and the lidar data frame.

I thank you for your time and assistance
